# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autofix_prs: true
  autoupdate_branch: dev
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: monthly

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
    -   id: trailing-whitespace
        exclude: \.cs$
    -   id: end-of-file-fixer
        exclude: \.cs$
    -   id: check-yaml
        exclude: \.cs$
    -   id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: "v0.14.14"
  hooks:
    - id: ruff-format # formatter
      types_or: [python, pyi, jupyter, toml]
      exclude: \.cs$
    - id: ruff # linter
      types_or: [python, pyi, jupyter, toml]
      args: [--fix]
      exclude: \.cs$
